import { Topic } from '../../models/models';

export const DART_OPERATORS: Record<string, Topic> = {
  equality: {
    title: 'Equality and relational operators',
    link: 'https://dart.dev/language/operators#equality-and-relational-operators',
    items: {
      'loose-equal': {
        id: 'loose-equal',
        link: 'https://dart.dev/language/operators#equality-and-relational-operators',
        name: 'Equality',
        code: '',
        example: '',
        output: '',
        bullets: ['Dart does not support type coercion'],
      },
      'strict-equal': {
        id: 'strict-equal',
        link: 'https://dart.dev/language/operators#equality-and-relational-operators',
        name: 'Equality',
        code: '==',
        example: '2 == 2',
        output: '// returns true',
        bullets: [
          'Checks whether its two operands are equal (value and type), returning a Boolean result',
          'Checks the content of arrays:\n[1, 2, 3] == [1, 2, 3] // returns true',
        ],
      },
      'loose-not-equal': {
        id: 'loose-not-equal',
        link: 'https://dart.dev/language/operators#equality-and-relational-operators',
        name: 'Inequality',
        code: '',
        example: '',
        output: '',
        bullets: ['Dart does not support type coercion'],
      },
      'strict-not-equal': {
        id: 'strict-not-equal',
        link: 'https://dart.dev/language/operators#equality-and-relational-operators',
        name: 'Inequality',
        code: '!=',
        example: '3 != 2',
        output: '// returns true',
        bullets: ['Checks whether its two operands are not equal, returning a Boolean result'],
      },
      'greater-than': {
        id: 'greater-than',
        link: 'https://dart.dev/language/operators#equality-and-relational-operators',
        name: 'Greater than',
        code: '>',
        example: '3 > 2',
        output: '// returns true',
        bullets: [
          'Returns true if the left operand is greater than the right operand, and false otherwise',
        ],
      },
      'less-than': {
        id: 'less-than',
        link: 'https://dart.dev/language/operators#equality-and-relational-operators',
        name: 'Less than',
        code: '<',
        example: '3 < 2',
        output: '// returns false',
        bullets: [
          'Returns true if the left operand is less than the right operand, and false otherwise',
        ],
      },
      'greater-or-equal': {
        id: 'greater-or-equal',
        link: 'https://dart.dev/language/operators#equality-and-relational-operators',
        name: 'Greater than or equal',
        code: '>=',
        example: '3 >= 3',
        output: '// returns true',
        bullets: [
          'Returns true if the left operand is greater than or equal to the right operand, and false otherwise',
        ],
      },
      'less-or-equal': {
        id: 'less-or-equal',
        link: 'https://dart.dev/language/operators#equality-and-relational-operators',
        name: 'Less than or equal',
        code: '<=',
        example: '3 <= 2',
        output: '// returns false',
        bullets: [
          'Returns true if the left operand is less than or equal to the right operand, and false otherwise',
        ],
      },
    },
  },
  logical: {
    title: 'Logical operators',
    link: 'https://dart.dev/language/operators#logical-operators',
    items: {
      not: {
        id: 'not',
        link: 'https://dart.dev/language/operators#logical-operators',
        name: 'Logical NOT',
        code: '!',
        example: '!true',
        output: '// returns false',
        bullets: ['Inverts the expression that follows (changes false to true, and vice versa)'],
      },
      or: {
        id: 'or',
        link: 'https://dart.dev/language/operators#logical-operators',
        name: 'Logical OR',
        code: '||',
        example: 'true || false',
        output: '// returns true',
        bullets: ['Returns true if one or more of its operands is true, and false otherwise '],
      },
      and: {
        id: 'and',
        link: 'https://dart.dev/language/operators#logical-operators',
        name: 'Logical AND',
        code: '&&',
        example: 'true && false',
        output: '// returns false',
        bullets: ['It will be true if all the operands are true. Otherwise it will be false'],
      },
    },
  },
};
