// Avoid == as it performs unpredictable type coercion.

import { Category } from '../../models/models';

export const LANGUAGE_OPERATORS: Record<string, Category> = {
  equality: {
    title: 'Equality and relational operators',
    documentation: '',
    items: [
      {
        id: 'loose-equal',
        documentation: '',
        name: '',
        code: '',
        example: '',
        output: '',
        bullets: [],
      },
      {
        id: 'strict-equal',
        documentation: '',
        name: '',
        code: '',
        example: '',
        output: '',
        bullets: [],
      },
      {
        id: 'loose-not-equal',
        documentation: '',
        name: '',
        code: '',
        example: '',
        output: '',
        bullets: [],
      },
      {
        id: 'strict-not-equal',
        documentation: '',
        name: '',
        code: '',
        example: '',
        output: '',
        bullets: [],
      },
      {
        id: 'greater-than',
        documentation: '',
        name: '',
        code: '',
        example: '',
        output: '',
        bullets: [],
      },
      {
        id: 'less-than',
        documentation: '',
        name: '',
        code: '',
        example: '',
        output: '',
        bullets: [],
      },
      {
        id: 'greater-or-equal',
        documentation: '',
        name: '',
        code: '',
        example: '',
        output: '',
        bullets: [],
      },
      {
        id: 'less-or-equal',
        documentation: '',
        name: '',
        code: '',
        example: '',
        output: '',
        bullets: [],
      },
    ],
  },
  logical: {
    title: 'Logical operators',
    documentation: '',
    items: [
      {
        id: 'not',
        documentation: '',
        name: '',
        code: '',
        example: '',
        output: '',
        bullets: [],
      },
      {
        id: 'or',
        documentation: '',
        name: '',
        code: '',
        example: '',
        output: '',
        bullets: [],
      },
      {
        id: 'and',
        documentation: '',
        name: '',
        code: '',
        example: '',
        output: '',
        bullets: [],
      },
    ],
  },
};
