// Avoid == as it performs unpredictable type coercion.

import { Category } from '../../models/models';

export const LANGUAGE_OPERATORS: Record<string, Category> = {
  equality: {
    title: 'Equality and relational operators',
    link: '',
    items: {
      'loose-equal': {
        id: 'loose-equal',
        link: '',
        name: '',
        code: '',
        example: '',
        output: '',
        bullets: [],
      },
      'strict-equal': {
        id: 'strict-equal',
        link: '',
        name: '',
        code: '',
        example: '',
        output: '',
        bullets: [],
      },
      'loose-not-equal': {
        id: 'loose-not-equal',
        link: '',
        name: '',
        code: '',
        example: '',
        output: '',
        bullets: [],
      },
      'strict-not-equal': {
        id: 'strict-not-equal',
        link: '',
        name: '',
        code: '',
        example: '',
        output: '',
        bullets: [],
      },
      'greater-than': {
        id: 'greater-than',
        link: '',
        name: '',
        code: '',
        example: '',
        output: '',
        bullets: [],
      },
      'less-than': {
        id: 'less-than',
        link: '',
        name: '',
        code: '',
        example: '',
        output: '',
        bullets: [],
      },
      'greater-or-equal': {
        id: 'greater-or-equal',
        link: '',
        name: '',
        code: '',
        example: '',
        output: '',
        bullets: [],
      },
      'less-or-equal': {
        id: 'less-or-equal',
        link: '',
        name: '',
        code: '',
        example: '',
        output: '',
        bullets: [],
      },
    },
  },
  logical: {
    title: 'Logical operators',
    link: '',
    items: {
      not: {
        id: 'not',
        link: '',
        name: '',
        code: '',
        example: '',
        output: '',
        bullets: [],
      },
      or: {
        id: 'or',
        link: '',
        name: '',
        code: '',
        example: '',
        output: '',
        bullets: [],
      },
      and: {
        id: 'and',
        link: '',
        name: '',
        code: '',
        example: '',
        output: '',
        bullets: [],
      },
    },
  },
};
